add external backend to allow calling out to pluggable script instead of directly processing
dvtirol/serles-acme pull request #1
Opened 2023-06-26 12:22 UTC by nneul

2023-06-26 16:39 UTC, nneul commented
I will in next day or so - still working on it, and can add it as an included example once I have it fully working and then can strip out the 'stuff specific to my deployment' to make it suitable for a general example.

2023-06-27 01:54 UTC, nneul commented
Example wrapper added to the examples-external directory that could be used as a starting point.

I was able to request a cert from an arbitrary server in my intranet, pointing to the serles installation, and it was handed back a fully valid LetsEncrypt signed cert chain.

2023-07-06 07:22 UTC, uedvt359 commented
Sorry, stressful week. I haven't forgotten about this, I'll take a look soon!

2023-07-25 11:25 UTC, uedvt359 commented
Hi, sorry it took me so long to review your code. I have a few questions regarding the architecture of the backend. Right now, you pass information about the csr/order as json on stdin. This is obviously not standardized (since there is no such standard). This means that all external/wrapper script need to be written specifically for serles-acme.

Given that your certbot script is already in python - why go to the trouble of exec'ing another process and serializing the data transmitted between them? Would you be open to submit your certbot-backend directly?

Or is the certbot wrapper just an example, and what you need is something else which you can't share? I'm not completely opposed to adding an 'external' backend (with all the nonstandard interfacing it needs), but I would prefer more tailored backends if possible and practical.

2023-07-25 12:09 UTC, nneul commented
The certbot backend was just an example based primarily on how existing code does it with openssl - it could potentially be ANY ACME client (or any other certificate obtaining mechanism). I could certainly make a specific tie-in directly to certbot pretty easily, though that wouldn't be as generalized in "allow a particular deployment to plug in whatever tool suits their needs without necessarily customizing serles' code".

Mainly the model was "add a plugin interface". 

For my utilization of certbot - I would likely have to add several additional configuration settings for the 'certbot specific plugin' since it will need to pass a number of additional parameters to certbot. The example external I provided was for native dns-route53 validation, but in my actual use case deployment, I can't directly use that, I actually need to have a custom hook to be able to allow certbot to deal with multiple _different_ AWS account credential sets depending on the particular domain being serviced, and that isn't supported natively. Figure I'll probably have a configuration setting to just add additional arguments to the certbot invocation.

If the 'pass via stdin' is primary concern with the particular external implementation, it would be pretty trivial to have that pass via a temporary directory+file. The subject DN and alt names should already be in the CSR itself and could be pulled from the CSR itself. The email isn't, but it's not clear that is really required -- I just passed that through cause it was available in the calling context.

I'll see what I can do about putting together a certbot specific backend since that would be more 'drop-in', but would definitely still like to see some variation of the generalized 'plugin/external' support that didn't require directly customizing the code.

2023-07-26 00:06 UTC, nneul commented
One thing that could be helpful for above - do you happen to have an example using that config file library that you are using to load in an array of values as opposed to a multiline string?

2023-08-16 18:26 UTC, uedvt359 commented
> Mainly the model was "add a plugin interface".
> but would definitely still like to see some variation of the generalized 'plugin/external' support that didn't require directly customizing the code.

Well, serles-acme already has a plugin interface; using python modules. they don't have to be loaded from within serles - as long as they can be found on the python path they can be imported.

For example, you can put `serles/backends/external.py` in `~/.local/lib/python3.*/site-packages/externalSerlesPlugin.py` and load it in the config with `backend = externalSerlesPlugin:Backend`. Or you could install it to e.g `/tmp/externalSerlesPlugin.py` and set `PYTHONPATH=/tmp` with the same config again.

Of course, I'd suggest modifying `certbot-wrapper.py` to provide a `class Backend` directly.

> do you happen to have an example using that config file library that you are using to load in an array of values as opposed to a multiline string?

I don't think python's ConfigParser can do that. splitting multiline strings is (afaict) the recommended practise.

2023-08-19 19:05 UTC, nneul commented
You were absolutely right on the "just do certbot directly" -- this is much cleaner.  Please review updates and let me know if this works for you.

2023-08-21 14:48 UTC, uedvt359 commented
I'll try to take a look at this this week. thanks for being patient with me :)

2023-08-22 13:44 UTC, uedvt359 requested changes
this is really, really cool! thanks for putting in the work to rewrite this as a direct backend. I'm 100% committed on merging this.

i've added quite a lot of notes; if you think some of these don't make sense, please say so.

2023-08-22 13:44 UTC, uedvt359 commented on config.ini.example
> +  ]
instead of passing extra configuration as a json array, have you considered providing the contents of a [cli.ini](https://eff-certbot.readthedocs.io/en/stable/using.html#configuration-file) file here instead? 

you could then write this into a temporary file in `__init__()` (and clean it up in `__del__()`). the config file has all the same options as the command line arguments, but doesn't have the problem of having to split it into an array ourselves (just write the whole `args` multi-line string into the tmpfile). i'd suggest a name change, e.g. `config`, then. this also allows comments inside the multiline string to document each statement.

iirc, config file entries have lower precedence than cli args; this means that you pass to subprocess.run can't be accidentally overwritten (which imo is a positive).

additional bonus if this is done: if certbot is used on the same machine in the usual way, its config won't spill into serles-certbot. this of course assumes that we always overwrite the config file, even if it's empty.

2023-08-22 13:44 UTC, uedvt359 commented on serles/backends/certbot.py
> +        self.path = "/usr/bin/certbot"
```suggestion
        self.path = "certbot"
```

should take it from the `$PATH`, right?

2023-08-22 13:44 UTC, uedvt359 commented on serles/backends/certbot.py
> +                fh.write(csr.decode('utf-8'))
```suggestion
            with open(csr_file, "wb") as fh:
                fh.write(csr)
```

2023-08-22 13:44 UTC, uedvt359 commented on docs/index.rst
> +------------------
please keep at h3 level (same for below)

2023-08-22 13:44 UTC, uedvt359 commented on docs/index.rst
> +
please document which config options need to be set for a usual setup. i'd presume this would mean `preferred-challenges = dns`, maybe some others (you're the expert here :) ) and a link to the [documentation](https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins)

2023-08-22 13:52 UTC, nneul commented on config.ini.example
> +  ]
Well, that's a great idea. Never even knew cli.ini existed for certbot. Will update.

2023-08-22 13:54 UTC, nneul commented on config.ini.example
> +  ]
Though I think at that point, I wouldn't even have it be passed in as contents with a temporary file - I'd just have it be a fixed config setting "provide a certbot cli.ini file".

2023-08-22 13:58 UTC, uedvt359 commented on config.ini.example
> +  ]
i think having all the configuration in a single place (serles' config file) would be nice. i can live with a seperate config file, too, though.

2023-08-22 14:01 UTC, uedvt359 commented on serles/backends/certbot.py
> +        self.path = "/usr/bin/certbot"
yeah, i know (this is one of the possibly bad ideas i mentioned above). given that serles is (hopefully) started through an init daemon, it's path should be well defined. i'm ok with leaving it at `/usr/bin`, but maybe add a check that the file exists and is executable

2023-08-22 14:03 UTC, nneul commented on config.ini.example
> +    "--logs-dir", "/local/acme/certbot/logs",
agreed, I'll put them in the example ini commented with an explanation of why you might want to have them, but not enabled by default.

2023-08-22 14:32 UTC, nneul commented on config.ini.example
> +  ]
ok. will see what I can do implementing support for both.

2023-08-22 14:36 UTC, uedvt359 commented on config.ini.example
> +  ]
i think the backend should check that exactly zero or one of `config` or `config-file` is provided, then (and raise if both are given). if neither, we should set `--config` to `/dev/null` (as to not accidentally pull in the global `/etc/letsencrypt/cli.ini` default config).

if that's too much work, i'm ok with sticking to an external config file only.

2023-08-22 15:23 UTC, nneul commented on config.ini.example
> +  ]
Updated, have a look at current code.

2023-08-22 15:23 UTC, nneul commented on serles/backends/certbot.py
> +        self.path = "/usr/bin/certbot"
Updated, have a look at current code.

2023-08-22 15:23 UTC, nneul commented on serles/backends/certbot.py
> +                fh.write(csr.decode('utf-8'))
Updated, have a look at current code.

2023-08-23 08:27 UTC, uedvt359 commented on examples-backends/certbot-cli.ini
> +#logs-dir=/local/acme/certbot/logs
please add this information to docs/index.rst

2023-08-23 12:15 UTC, nneul commented on serles/backends/certbot.py
> +            # Write explicit configuration to temporary file if a config file is not provided
Main reason - lack of an existing "temporary dir" context for the life of the server. If a temporary dir context wrapped the entire server lifecycle and the temporary dir name/prefix was made available to the backends, that would make sense to use for this since indeed it does not change throughout invocation. 

It could be rigged inside the plugin as structured currently, but would be messy with the need to trap for cleanup.

2023-08-23 12:21 UTC, nneul commented on examples-backends/certbot-cli.ini
> +#logs-dir=/local/acme/certbot/logs
done

2023-08-29 10:56 UTC, merged

2023-09-03 02:13 UTC, nneul commented
@uedvt359 Any plans to do a new pypi release?

2023-09-04 07:03 UTC, uedvt359 commented
yeah, a release is overdue. I'll try to find time for it soon

2024-01-12 08:04 UTC, uedvt359 commented
@nneul  - took me long enough, but there is finally a 1.1.0 release on pypi.