Implement DNS-01 challenge
dvtirol/serles-acme pull request #9
Opened 2024-11-03 16:08 UTC by syberalexis

Add implementation for DNS-01 challenge and enable it
Add pytests for the new implementation

Refer to #8

2024-11-04 09:48 UTC, uedvt359 requested changes
Thank you a lot! I only had time for a cursory look, but it looks well-implemented. I appreciate you implementing tests as well. I'll need to run the test suite and compare it against the specification, still.

i've added some inline notes. for further changes, i'd prefer rebased commits, if you can.

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> +import dns.resolver
new requirement needs to be added to setup.py

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> +        return "incorrectResponse", f"no token found in TXT record {expect}"
```suggestion
    for answer in answers:
        if expect == answer.strings[0].decode():
            break
    else:
        return "incorrectResponse", f"no token found in TXT record {expect}"
```
(yes, that's the correct indentation for this else :) )

the `.strip('"')` makes me a bit queasy. i believe we can get to the challenge string with the code above, although we need to make sure it doesn't raise an exception (if .strings is empty or contains non-ascii characters)

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> +        answers = dns.resolver.query(f"_acme-challenge.{host}", "TXT")
```
>>> dns.resolver.query("tirol.gv.at", "TXT")
<stdin>:1: DeprecationWarning: please use dns.resolver.resolve() instead
```

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> -
nit-pick: please leave functions double-spaced. also applies to new functions added here.

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> +def calculate_sha256(challenge):
i'd prefer to inline this function, since it is specific to the dns challenge

2024-11-04 09:48 UTC, uedvt359 commented on tests/test_challengefuns.py
> +    # No challenge are unsupported now !
don't think we need this any more, please just remove it.

2024-11-04 09:48 UTC, uedvt359 commented on serles/challenge.py
> +    # When it´s a wildcard domain, remove the wildcard
i believe we need special handling for wildcard certs elsewhere, too. i'd consider this out of scope of this pr, though; we can handle it later (it should at least be a separate commit, if you intend to include it in this PR).

ctrl-f for "wildcard" yields results in:
https://datatracker.ietf.org/doc/html/rfc8555#section-7.1.3
https://datatracker.ietf.org/doc/html/rfc8555#section-7.1.4

2024-11-04 10:21 UTC, syberalexis commented on serles/challenge.py
> +import dns.resolver
You already add it with dnspython package

2024-11-04 10:23 UTC, uedvt359 commented on serles/challenge.py
> +import dns.resolver
oops, completely forgot we already depend on that. sorry for the noise

2024-11-04 11:39 UTC, syberalexis commented on serles/challenge.py
> +        return "incorrectResponse", f"no token found in TXT record {expect}"
Your `else` proposal don't work if DNS return multiple TXT !? It's return error at the first answer if it don´t match.
`makes me a bit queasy`... I'm not a Python developer...
I didn't know string `decode` function, thanks.
I don't understand how works `.strings[X]`, i trust you. But managing strings with array index like this is a very bad practice, possibly a lib or language failure, idk...

2024-11-04 11:39 UTC, syberalexis commented on serles/challenge.py
> +        answers = dns.resolver.query(f"_acme-challenge.{host}", "TXT")
Oh i didn't see this, tkanks

2024-11-04 11:39 UTC, syberalexis commented on serles/challenge.py
> -
Ok, if you want ^^

2024-11-04 11:44 UTC, uedvt359 commented on serles/challenge.py
> +        return "incorrectResponse", f"no token found in TXT record {expect}"
> Your else proposal don't work if DNS return multiple TXT

yes, it does. this is a for-else loop, not an if-else statement. it's a lesser used feature, but in short: if the loop is not `break`ed, the else clause of the for-loop is triggered.

`.strings` is an [attribute of the dnspython response object](https://dnspython.readthedocs.io/en/stable/rdata-subclasses.html#dns.rdtypes.ANY.TXT.TXT.strings), which is a list of the content.

2024-11-04 13:03 UTC, syberalexis commented on serles/challenge.py
> +        return "incorrectResponse", f"no token found in TXT record {expect}"
Obviously, `answers` is returned as an array of string with `resolve()` instead of `query()`

2024-11-04 13:50 UTC, uedvt359 requested changes
thanks for the quick update. we're getting really close. i still haven't run your code, but i only have one remaining piece of feedback before i'll start testing it out.

2024-11-04 15:12 UTC, syberalexis commented on serles/challenge.py
> +        if expect == answer:
Hum ok :)

I think, it's my data tests that fuck my brain with doesn't use `.strings`
Oh yes, i see it, i don't make the link with `.string[0]`, it's good for me :)

2024-11-05 15:17 UTC, uedvt359 commented
i have installed your branch on one of our development machines and successfully generated a certificate using it! this makes me very happy :)

```
[root@someserver ~]# REQUESTS_CA_BUNDLE=/etc/pki/tls/cert.pem /usr/bin/certbot certonly --config /etc/letsencrypt/cli-rzapi-someserver.ini --force-renewal  --manual --preferred-challenges dns -v
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate for someserver.example.com
Performing the following challenges:
dns-01 challenge for someserver.example.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name:

_acme-challenge.someserver.example.com.

with the following value:

nfTaYBNG7Dj6BB470-_o808wAMRvzIa3ssE1gR1xx48

Before continuing, verify the TXT record has been deployed. Depending on the DNS
provider, this may take some time, from a few seconds to multiple minutes. You can
check if it has finished deploying with aid of online tools, such as the Google
Admin Toolbox: https://toolbox.googleapps.com/apps/dig/#TXT/_acme-challenge.someserver.example.com.
Look for one or more bolded line(s) below the line ';ANSWER'. It should show the
value(s) you've just added.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Continue
Waiting for verification...
Cleaning up challenges

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/someserver.example.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/someserver.example.com/privkey.pem
This certificate expires on 2025-02-03.
These files will be updated when the certificate renews.

NEXT STEPS:
- This certificate will not be renewed automatically. Autorenewal of --manual certificates requires the use of an authentication hook script (--manual-auth-hook) but one was not provided. To renew this certificate, repeat this same certbot command before the certificate's expiry date.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[root@someserver ~]# cat /etc/letsencrypt/cli-rzapi-someserver.ini
server = https://serles.example.com:8443/directory
domains = someserver.example.com
register-unsafely-without-email = True
keep-until-expiring = True
agree-tos = True
key-type = rsa
rsa-key-size = 4096
```

2024-11-05 17:43 UTC, syberalexis commented on tests/test_challengefuns.py
> +    def test_dns_challenge_nonameservers(self):
Arf, i don't see that

2024-11-05 17:49 UTC, syberalexis commented on tests/test_challengefuns.py
Ah yes, i don´t see that !
Thanks for the html generating command

2024-11-06 10:04 UTC, merged

2024-11-06 10:05 UTC, uedvt359 commented
Thanks, great work!

2024-11-06 11:02 UTC, syberalexis commented
Thank you for corrections and help :)